name: File Size Checker
description: Checks the file size of new files to ensure we limit large file changes to the repository

branding:
  icon: 'file'
  color: 'red'

inputs:
  max_file_size_kib:
    description: 'Maximum allowed file size for new files in Kibibytes (KiB)'
    required: true
    default: '20'
  base_sha:
    description: 'Base commit SHA to compare against for new files'
    required: true
    default: ${{ github.event.pull_request.base.sha }}
  head_sha:
    description: 'Head commit SHA to compare against for new files'
    required: true
    default: ${{ github.event.pull_request.head.sha }}
# TODO: implement these options
#  fail_on_large_files:
#    description: "Whether to fail the action when large files are found"
#    required: false
#    default: "false"
#  exclude_patterns:
#    description: "Comma-separated list of file patterns to exclude (e.g., '*.log,*.tmp')"
#    required: false
#    default: ""
#  include_patterns:
#    description: "Comma-separated list of file patterns to include (e.g., '*.zip,*.tar.gz')"
#    required: false
#    default: ""
#  check_all_commits:
#    description: 'Whether to check all commits between base and head'
#    required: false
#    default: 'false'

outputs:
  violations_list:
    description: "List of files that exceeded the maximum size limit"
    value: ${{ steps.size_check.outputs.violations_list }}

runs:
  using: 'composite'
  steps:
    - id: size_check
      shell: sh
      env:
        max_file_size_kib: ${{ inputs.max_file_size_kib }}
        BASE_SHA: ${{ inputs.base_sha }}
        HEAD_SHA: ${{ inputs.head_sha }}
      run: ./file_size_checker.sh
